import type { NextPage } from "next";
import Head from "next/head";

import CustomHeader from "../containers/CustomHeader";

import Container from "@mui/material/Container";

import HomePageItem from "../components/HomePageItem";
import MostRequestedBets from "../containers/MostRequestedBets";
import SearchBets from "../containers/SearchBets";

import { useState } from "react";


const Home: NextPage = () => {

    const [listSize, setListSize] = useState(6);
    const [mostRequestedBets, setMostRequestedBets] = useState([]);

    const seeMoreHandler = () => {
        setListSize(listSize + 5);
    }

    return (
        <div>
            <Head>
                <title>Matchingbet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <CustomHeader/>
            <Container>
                <HomePageItem title="Buscar Apostas">
                    <SearchBets/>
                </HomePageItem>

                <HomePageItem
                    title="Apostas mais acessadas"
                    showSeeMore={true}
                    seeMoreHandler={seeMoreHandler}
                >
                    <MostRequestedBets mostRequestedBets={mostRequestedBets} size={listSize}/>
                </HomePageItem>
            </Container>

            {/* <CreateBet/> */}
        </div>
    );
};

export default Home;
