import type {NextPage} from "next";
import Head from "next/head";

import CustomHeader from "../components/CustomHeader";

import Container from "@mui/material/Container";

import HomePageItem from "../components/HomePageItem/HomePageItem";
import MostRequestedBets from "../components/MostRequestedBets/MostRequestedBets";
import SearchBets from "../components/SearchBets";

import {ThemeProvider} from "@mui/material/styles";
import { theme } from "../styles/theme";
import BetCardProps from "../models/Bet";
import {useState} from "react";
import CreateBet from "../components/CreateBetButton";


export async function getServerSideProps() {
    const response = await fetch("http://localhost:3000/api/bets");
    const mostRequestedBets = await response.json();
    return {
        props: {
            mostRequestedBets,
        },
    }
}

interface HomePageProps {
    mostRequestedBets: Array<BetCardProps>;
}

const Home: NextPage<HomePageProps> = ({mostRequestedBets}) => {

    const [listSize, setListSize] = useState(6);

    const seeMoreHandler = () => {
        setListSize(listSize + 5);
    }

    return (
        <ThemeProvider theme={theme}>
            <Head>
                <title>Matchingbet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <CustomHeader/>
            <Container>
                <HomePageItem title="Buscar Apostas">
                    <SearchBets/>
                </HomePageItem>

                <HomePageItem
                    title="Apostas mais acessadas"
                    showSeeMore={true}
                    seeMoreHandler={seeMoreHandler}
                >
                    <MostRequestedBets mostRequestedBets={mostRequestedBets} size={listSize}/>
                </HomePageItem>
            </Container>

            <CreateBet/>
        </ThemeProvider>
    );
};

export default Home;
