import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

import Header from "../components/header";

import Container from "@mui/material/Container";

import SearchBets from "../components/search-bets";
import MostRequestedBest from "../components/most-requested-bets/most-requested-bets";
import SectionGroup from "../components/section-group/section-group";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Matchingbet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container>
        <SectionGroup title="Buscar Apostas">
          <SearchBets />
        </SectionGroup>

        <SectionGroup title="Apostas mais acessadas">
          <MostRequestedBest />
        </SectionGroup>
      </Container>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
